dist: trusty

language: python

addons:
  hosts: test_site
  mariadb: 10.3

jobs:
  include:
  - name: "Python 2.7 Server Side Test"
    python: 2.7
    script: bench --site test_site run-tests --app erpnext --coverage

  - name: "Python 3.6 Server Side Test"
    python: 3.6
    script: bench --site test_site run-tests --app erpnext --coverage

  - name: "Python 2.7 Patch Test"
    python: 2.7
    before_script:
      - wget http://build.erpnext.com/20171108_190013_955977f8_database.sql.gz
      - bench --force restore ~/frappe-bench/20171108_190013_955977f8_database.sql.gz --mariadb-root-password travis
    script: bench --site test_site migrate

  - name: "Python 3.6 Patch Test"
    python: 3.6
    before_script:
      - wget http://build.erpnext.com/20171108_190013_955977f8_database.sql.gz
      - bench --site test_site --force restore ~/frappe-bench/20171108_190013_955977f8_database.sql.gz --mariadb-root-password travis
    script: bench --site test_site migrate

install:
  - cd ~
  - nvm install 10

  - git clone https://github.com/frappe/bench --depth 1
  - pip install -e ./bench

  - git clone https://github.com/frappe/frappe --branch $TRAVIS_BRANCH --depth 1
  - bench init --frappe-path ~/frappe --python $(which python) frappe-bench

  - mkdir ~/frappe-bench/sites/test_site
  - cp -r $TRAVIS_BUILD_DIR/.travis/site_config.json ~/frappe-bench/sites/test_site/

before_script:
  - mysql -u root -e "SET GLOBAL character_set_server = 'utf8mb4'"
  - mysql -u root -e "SET GLOBAL collation_server = 'utf8mb4_unicode_ci'"

  - mysql -u root -e "CREATE DATABASE test_frappe"
  - mysql -u root -e "CREATE USER 'test_frappe'@'localhost' IDENTIFIED BY 'test_frappe'"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON \`test_frappe\`.* TO 'test_frappe'@'localhost'"

  - mysql -u root -e "UPDATE mysql.user SET Password=PASSWORD('travis') WHERE User='root'"
  - mysql -u root -e "FLUSH PRIVILEGES"

  - cd ~/frappe-bench
  - bench get-app erpnext $TRAVIS_BUILD_DIR
  - bench --site test_site reinstall --mariadb-root-username root --mariadb-root-password travis --yes
  - bench --site test_site scheduler disable
  - sed -i 's/9000/9001/g' sites/common_site_config.json
  - bench start &
  - sleep 10

after_script:
  - pip install python-coveralls
  - coveralls -b apps/erpnext -d ../../sites/.coverage
